version: '3'
services:
    moth-new:
        #image: cojam/moth:0.0.3.8-alpine-3.14
        #image: cojam/moth:0.0.4.2-alpine-3.14
        #image: cojam/moth:0.0.4.6-alpine-3.14
        #image: cojam/moth:0.0.5.6-alpine-3.14
        #image: cojam/moth:0.0.5.9-alpine-3.14
        #image: cojam/moth:0.0.6.7-alpine-3.14
        #image: cojam/moth:0.0.7.1-alpine-3.14
        #image: cojam/moth:0.0.8.7-alpine-3.15
        #image: cojam/moth:0.0.9.2-alpine-3.15
        #image: cojam/moth:0.0.9.5-alpine-3.15
        #image: cojam/moth:0.0.9.8-alpine-3.15
        # image: cojam/moth:0.1.0.6-alpine-3.15
        # image: cojam/moth:0.1.3.4-alpine3.17
        image: cojam/moth:0.1.2.2-alpine-3.16-arm64
        container_name: moth-new
        restart: unless-stopped
        ports:
            - 8276:8276
            - 8277:8277
        volumes:
            - ./cert:/moth/cert
            - ./conf:/moth/conf
            - ./html:/moth/html
            - ./data:/moth/data
            - ./log:/moth/log