export const videoEncoderSettings = {
  'video/h264': {
    high: {
      codec: 'avc1.42E01F',
      width: 1280,
      height: 720,
      bitrate: 8000000,
      bitrateMode: 'constant',
      framerate: 24,
      interval: 48,
      latencyMode: 'realtime',
      avc: { format: 'annexb' },
      //hardwareAcceleration: 'prefer - hardware',
    },
    low: {
      codec: 'avc1.42E01F',
      width: 640,
      height: 480,
      bitrate: 4000000,
      bitrateMode: 'constant',
      framerate: 30,
      interval: 60,
      latencyMode: 'realtime',
      avc: { format: 'annexb' },
      //hardwareAcceleration: 'prefer - hardware',
    },
  },
  'video/vp8': {
    high: {
      codec: 'vp8',
      width: 1280,
      height: 720,
      bitrate: 8000000,
      bitrateMode: 'constant',
      framerate: 24,
      interval: 60,
      latencyMode: 'realtime',
    },
    low: {
      codec: 'vp8',
      width: 1280,
      height: 720,
      bitrate: 4000000,
      bitrateMode: 'constant',
      framerate: 15,
      interval: 60,
      latencyMode: 'realtime',
    },
  },
  'video/vp9': {
    high: {
      codec: 'vp09.00.31.08',
      width: 1280,
      height: 720,
      bitrate: 8000000,
      bitrateMode: 'constant',
      framerate: 24,
      interval: 60,
      latencyMode: 'realtime',
    },
    low: {
      codec: 'vp09.00.31.08',
      width: 1280,
      height: 720,
      bitrate: 4000000,
      bitrateMode: 'constant',
      framerate: 15,
      interval: 60,
      latencyMode: 'realtime',
    },
  },
  'video/av1': {
    high: {
      codec: 'av01.0.05M.10',
      width: 1280,
      height: 720,
      bitrate: 8000000,
      bitrateMode: 'constant',
      framerate: 24,
      interval: 60,
      latencyMode: 'realtime',
    },
    low: {
      codec: 'av01.0.05M.10',
      width: 1280,
      height: 720,
      bitrate: 4000000,
      bitrateMode: 'constant',
      framerate: 15,
      interval: 60,
      latencyMode: 'realtime',
    },
  },
};

export const AudioEncoderSettings = {
  'audio/opus': {
    /*high: {
      codec: 'avc1.42E01F',
      width: 1280,
      height: 720,
      bitrate: 8000000,
      bitrateMode: 'constant',
      framerate: 24,
      interval: 48,
      latencyMode: 'realtime',
      avc: { format: 'annexb' },
      //hardwareAcceleration: 'prefer - hardware',
    },
    low: {
      codec: 'avc1.42E01F',
      width: 640,
      height: 480,
      bitrate: 4000000,
      bitrateMode: 'constant',
      framerate: 30,
      interval: 60,
      latencyMode: 'realtime',
      avc: { format: 'annexb' },
      //hardwareAcceleration: 'prefer - hardware',
    },*/
  },
  'audio/lyra': {
    /*high: {
      codec: 'vp8',
      width: 1280,
      height: 720,
      bitrate: 8000000,
      bitrateMode: 'constant',
      framerate: 24,
      interval: 60,
      latencyMode: 'realtime',
    },
    low: {
      codec: 'vp8',
      width: 1280,
      height: 720,
      bitrate: 4000000,
      bitrateMode: 'constant',
      framerate: 15,
      interval: 60,
      latencyMode: 'realtime',
    },*/
  },
};
